### ISSUE TITLE
Ajouter les diaporamas des conférences passées

### ISSUE THREAD

**Issue by EtienneReith** [CodeursEnSeine/CodeursEnSeine-site#39]
Tout est dans le titre ;-)

**Comment by PierreLeresteux** [comment]
Désolé mais le titre n'est pas assez parlant pour moi ... j'ai du mal à comprendre ce qui est demandé ... Tu peux expliquer un peu plus @EtienneReith  ? Merci

**Comment by EtienneReith** [comment]
Désolé, ce n'était effectivement pas assez clair.
Une image vaut probablement mieux qu'un long discours :
![codeurenseine_ajoutliens](https://user-images.githubusercontent.com/43985061/46869262-6ea4a680-ce2b-11e8-809f-0e6414205797.png)

Mais ajoutons tout de même un discours:
J'aurais aimé ressortir quelques chiffres du talk "Impact écologique du web" (que je n'avais bien sur pas pris en notes), et j'ai été fort attristé de me rendre compte que les diapos n'étaient pas disponibles. Je pense que c'est une belle valeur ajoutée de les archiver (quand elles ont un sens et que ce n'est pas du live coding à 90%).

**Comment by PierreLeresteux** [comment]
Ok tu parles des présentations des conférenciers lors des meetups ... 

Bonne remarque ... Merci ;)

**Comment by yoannfleurydev** [comment]
![Hello](https://user-images.githubusercontent.com/3920615/49400098-8588ba80-f743-11e8-87d3-1cfc09a29b04.png)

Hello. Déjà, merci pour l'idée, c'est quelque chose de vraiment intéressant ! 👍 
Et bonne nouvelle pour toi @EtienneReith, je viens de pousser une mise à jour du site qui contient la présentation que tu souhaitais.

⚠️ Je ne garanti pas qu'à l'avenir on ait toutes les présentations comme cela. Mais juste une note au cas où quelqu'un passe par là à l'avenir, le site est open-source, il est donc possible de contribuer via une [Pull Request](https://help.github.com/articles/about-pull-requests/) sur ce dépôt et d'insérer le lien des présentations directement sur les markdown des meetups qui se trouvent dans le dossier [`_posts/meetups`](https://github.com/CodeursEnSeine/CodeursEnSeine-site/tree/gh-pages/_posts/meetups). 
En général, la plupart des speakers 🗣  partagent leurs présentations à la suite du meetup (souvent sur Twitter), il est donc possible de récupérer le lien comme cela. Sinon, il est possible de gentiment leur demander de partager leur présentation, la plupart le feront.

Encore merci pour ton retour @EtienneReith 😃
